// ─── Mil Platôs — 30 Presets (jornada completa CsO) ─────────────────────────
import type { MPPreset } from './milplatosTypes';

export const MP_PRESETS: MPPreset[] = [
  // ── 1-5: ESTRATIFICAÇÃO (Corpo com Órgãos) ────────────────────────────────
  { id: 'organismo-puro', name: 'Organismo Puro', icon: '⬡',
    description: 'Hierarquia máxima. Órgãos rígidos, zero plasticidade.',
    plateauRef: 'Platô 6 · 28 de novembro de 1947: Como criar para si um Corpo sem Órgãos',
    theory: 'O organismo é o inimigo do CsO. Deleuze e Guattari descrevem como o corpo se organiza em órgãos com funções fixas, criando uma hierarquia que captura os fluxos de intensidade. O organismo puro é o corpo totalmente estratificado: cada parte tem função, cada fluxo tem direção. "Os estratos são atos de captura, são como buracos negros ou oclusões que se esforçam para reter tudo o que estiver ao alcance." Observe como os órgãos mantêm posições rígidas e as conexões são espessas — é o corpo enquanto máquina funcional, antes de qualquer linha de fuga.',
    params: { organismo:.95, intensidade:.10, hierarquia:.90, rigidez:.90, desorganizacao:.02, crueldade:.80, antiHabito:.02, multiplicidade:.05, linhasDeFuga:.02, territorializacao:.85, reterritorializacao:.70, hubs:.75, esquecimento:.02, ruido:.05, densidade:.30 },
    overlays: ['cso','afetos','connections','heatTerritory'] },

  { id: 'estratos-geologicos', name: 'Estratos Geológicos', icon: '▤',
    description: 'Camadas sedimentares. Territórios profundos, sem mobilidade.',
    plateauRef: 'Platô 3 · 10.000 a.C.: A geologia da moral',
    theory: '"A geologia da moral" descreve como a matéria se organiza em estratos — camadas de sedimentação que capturam os fluxos. O estrato é dupla articulação: conteúdo e expressão. Deleuze e Guattari distinguem três grandes estratos: o físico-químico, o orgânico e o antropomórfico. Cada camada se deposita sobre a anterior, endurecendo, territorializando. O campo de território (âmbar) mostra essa sedimentação: a memória encarnada na matéria, o passado que se recusa a soltar.',
    params: { organismo:.85, intensidade:.15, hierarquia:.80, rigidez:.85, desorganizacao:.05, crueldade:.75, antiHabito:.03, multiplicidade:.08, linhasDeFuga:.03, territorializacao:.90, reterritorializacao:.65, hubs:.60, esquecimento:.03, ruido:.08, densidade:.35 },
    overlays: ['cso','afetos','heatTerritory','connections'] },

  { id: 'aparelho-estado', name: 'Aparelho de Estado', icon: '🏛',
    description: 'Captura estatal. Hubs dominantes capturam todos os fluxos.',
    plateauRef: 'Platô 13 · 7000 a.C.: Aparelho de captura',
    theory: '"Aparelho de captura" analisa como o Estado opera por captura: os fluxos que circulam livremente são interceptados, codificados, sobrecodificados. O Estado não nasce da guerra — precede a guerra, opera por antecipação. Os hubs no rizoma são pontos de captura que centralizam conexões, criando hierarquia onde havia multiplicidade. "O Estado é soberania. Mas a soberania só reina sobre aquilo que é capaz de interiorizar." Observe como poucos nós dominam toda a rede — é a centralização como mecanismo de poder.',
    params: { organismo:.80, intensidade:.20, hierarquia:.85, rigidez:.75, desorganizacao:.08, crueldade:.65, antiHabito:.05, multiplicidade:.15, linhasDeFuga:.05, territorializacao:.70, reterritorializacao:.60, hubs:.90, esquecimento:.05, ruido:.10, densidade:.40 },
    overlays: ['rizoma','connections','heatTerritory'] },

  { id: 'sobrecodificacao', name: 'Sobrecodificação', icon: '⧈',
    description: 'Códigos sobre códigos. Rigidez extrema com pressão interna.',
    plateauRef: 'Platô 5 · 587 a.C. – 70 d.C.: Sobre alguns regimes de signos',
    theory: '"Sobre alguns regimes de signos" descreve como os códigos se empilham: signos sobre signos, interpretações sobre interpretações. A sobrecodificação é o excesso de estratificação — quando o sistema produz mais regulação do que pode suportar, gerando pressão interna. O regime significante é paranóico: tudo faz signo, tudo remete a um centro de significância. Observe a tensão: as conexões são rígidas, mas a crueldade se acumula — a pressão que vai explodir está ali, latente.',
    params: { organismo:.85, intensidade:.25, hierarquia:.80, rigidez:.80, desorganizacao:.10, crueldade:.70, antiHabito:.05, multiplicidade:.10, linhasDeFuga:.08, territorializacao:.75, reterritorializacao:.55, hubs:.65, esquecimento:.05, ruido:.12, densidade:.45 },
    overlays: ['cso','afetos','connections'] },

  { id: 'maquina-despotica', name: 'Máquina Despótica', icon: '◈',
    description: 'Significante despótico. Um centro irradia ordem totalitária.',
    plateauRef: 'Platô 13 · 7000 a.C.: Aparelho de captura',
    theory: 'O déspota é o significante mestre que subordina todos os fluxos a um centro único. Em "Aparelho de captura", Deleuze e Guattari mostram como a máquina despótica opera por sobrecodificação total: um ponto irradia ordem sobre todos os outros, apagando a multiplicidade. "O déspota faz a terra, o território, depender de sua unidade superior transcendente." É a forma mais extrema de captura: hub dominante, hierarquia máxima, território como propriedade do centro.',
    params: { organismo:.90, intensidade:.15, hierarquia:.90, rigidez:.85, desorganizacao:.03, crueldade:.80, antiHabito:.02, multiplicidade:.05, linhasDeFuga:.02, territorializacao:.80, reterritorializacao:.75, hubs:.85, esquecimento:.02, ruido:.05, densidade:.35 },
    overlays: ['connections','heatTerritory','cso','afetos'] },

  // ── 6-10: TRANSIÇÃO (primeiras fissuras) ──────────────────────────────────
  { id: 'fissura-inicial', name: 'Fissura Inicial', icon: '⊘',
    description: 'Primeiras rachaduras. Órgãos começam a perder rigidez.',
    plateauRef: 'Platô 8 · 1874: Três novelas, ou "O que se passou?"',
    theory: '"Três novelas" explora as linhas que compõem uma vida: a linha molar (segmentos rígidos), a linha molecular (fissuras) e a linha de fuga. A fissura inicial é o primeiro tremor molecular — algo se moveu sob a superfície antes que a estrutura perceba. "Alguma coisa se passou, mas não sei dizer exatamente o quê." Observe como a rigidez começa a ceder: os órgãos já não mantêm suas posições com a mesma firmeza, as intensidades começam a circular com mais liberdade.',
    params: { organismo:.70, intensidade:.30, hierarquia:.65, rigidez:.60, desorganizacao:.20, crueldade:.55, antiHabito:.15, multiplicidade:.15, linhasDeFuga:.10, territorializacao:.60, reterritorializacao:.45, hubs:.50, esquecimento:.10, ruido:.18, densidade:.45 },
    overlays: ['cso','afetos','connections'] },

  { id: 'tremor-organico', name: 'Tremor Orgânico', icon: '〰',
    description: 'Vibração interna. Intensidades crescem dentro da estrutura.',
    plateauRef: 'Platô 6 · 28 de novembro de 1947: Como criar para si um Corpo sem Órgãos',
    theory: 'No platô do CsO, Deleuze e Guattari descrevem como as intensidades começam a percorrer o corpo antes que a organização se dissolva. O tremor é a vibração molecular que precede a desestratificação — os afetos crescem dentro da estrutura sem ainda rompê-la. "As intensidades se produzem em um spatium ele mesmo intensivo, que não comporta distâncias nem medidas." Ative a camada de Consistência (azul) para ver as intensidades se acumulando nos interstícios da organização.',
    params: { organismo:.65, intensidade:.40, hierarquia:.55, rigidez:.55, desorganizacao:.25, crueldade:.50, antiHabito:.20, multiplicidade:.20, linhasDeFuga:.15, territorializacao:.50, reterritorializacao:.40, hubs:.40, esquecimento:.12, ruido:.22, densidade:.50 },
    overlays: ['cso','afetos','heatConsistency'] },

  { id: 'erosao-territorial', name: 'Erosão Territorial', icon: '⊟',
    description: 'Territórios se dissolvem lentamente. Memória enfraquece.',
    plateauRef: 'Platô 11 · 1837: Acerca do ritornelo',
    theory: '"Do ritornelo" descreve como o território se forma e se dissolve. O território não é um espaço geográfico — é um ato expressivo, um motivo que marca e organiza. A erosão territorial é a desterritorialização lenta: as marcas que definem o território começam a se apagar, a memória enfraquece, os limites se tornam porosos. "O território é o produto de uma territorialização dos meios e dos ritmos." Observe o campo de território (âmbar) se dissolvendo gradualmente.',
    params: { organismo:.55, intensidade:.40, hierarquia:.50, rigidez:.45, desorganizacao:.30, crueldade:.45, antiHabito:.25, multiplicidade:.25, linhasDeFuga:.20, territorializacao:.35, reterritorializacao:.30, hubs:.35, esquecimento:.25, ruido:.25, densidade:.50 },
    overlays: ['heatTerritory','cso','afetos'] },

  { id: 'primeira-ruptura', name: 'Primeira Ruptura', icon: '⚡',
    description: 'Crueldade excede limiar. Primeira ruptura violenta.',
    plateauRef: 'Platô 9 · 1933: Micropolítica e segmentaridade',
    theory: '"Micropolítica e segmentaridade" distingue entre segmentaridade dura (molar) e flexível (molecular). A primeira ruptura é o momento em que a crueldade acumulada — intensidades reprimidas dentro da organização — excede o limiar e rompe a estrutura molar. "Tudo é político, mas toda política é ao mesmo tempo macropolítica e micropolítica." O anel de ruptura (vermelho) marca o ponto onde a acumulação se tornou insustentável — é o evento, a singularidade que muda tudo.',
    params: { organismo:.60, intensidade:.50, hierarquia:.50, rigidez:.45, desorganizacao:.35, crueldade:.25, antiHabito:.30, multiplicidade:.20, linhasDeFuga:.25, territorializacao:.40, reterritorializacao:.30, hubs:.35, esquecimento:.15, ruido:.30, densidade:.55 },
    overlays: ['cso','afetos','connections','flights'] },

  { id: 'descodificacao', name: 'Descodificação', icon: '⊗',
    description: 'Códigos se soltam. Anti-hábito começa a dominar.',
    plateauRef: 'Platô 5 · 587 a.C. – 70 d.C.: Sobre alguns regimes de signos',
    theory: 'A descodificação é o processo inverso da sobrecodificação: os códigos se soltam, os signos perdem suas referências fixas. O anti-hábito começa a dominar — cada conexão pode ser re-feita de forma improvável, cada signo pode significar outra coisa. "Os fluxos descodificados escorrem por todos os lados, atravessam as muralhas." Observe como CsO e Rizoma começam a coexistir: a hierarquia orgânica e o grafo acêntrico ocupam o mesmo espaço, criando tensão produtiva.',
    params: { organismo:.50, intensidade:.50, hierarquia:.40, rigidez:.40, desorganizacao:.40, crueldade:.40, antiHabito:.40, multiplicidade:.30, linhasDeFuga:.30, territorializacao:.35, reterritorializacao:.25, hubs:.30, esquecimento:.20, ruido:.30, densidade:.55 },
    overlays: ['cso','afetos','rizoma'] },

  // ── 11-15: DESTERRITORIALIZAÇÃO ───────────────────────────────────────────
  { id: 'desterritorializacao', name: 'Desterritorialização', icon: '↗',
    description: 'Fuga ativa dos territórios. Conexões se rompem.',
    plateauRef: 'Platô 14 · 1440: O liso e o estriado',
    theory: '"O liso e o estriado" descreve dois espaços: o estriado (organizado, medido, territorizado) e o liso (aberto, intensivo, nômade). A desterritorialização é a passagem do estriado ao liso — o abandono ativo dos territórios. "O espaço liso é percorrido por um traço que não tem começo nem fim, que passa entre os pontos." As linhas de fuga (traços pontilhados roxos) mostram essa travessia: conexões improváveis que perfuram o espaço estriado.',
    params: { organismo:.40, intensidade:.55, hierarquia:.30, rigidez:.30, desorganizacao:.50, crueldade:.35, antiHabito:.50, multiplicidade:.35, linhasDeFuga:.60, territorializacao:.20, reterritorializacao:.15, hubs:.20, esquecimento:.30, ruido:.35, densidade:.55 },
    overlays: ['flights','cso','afetos','rizoma'] },

  { id: 'nomadismo', name: 'Nomadismo', icon: '↝',
    description: 'Máquina de guerra nômade. Mobilidade constante.',
    plateauRef: 'Platô 12 · 1227: Tratado de nomadologia — A máquina de guerra',
    theory: '"Tratado de nomadologia" opõe a máquina de guerra nômade ao aparelho de Estado. O nômade não é quem viaja, mas quem ocupa o espaço liso: sem território fixo, sem hierarquia, mobilidade como modo de existência. "O nômade tem um território, segue trajetos costumeiros, vai de um ponto a outro, não ignora os pontos. Mas a questão é que o ponto existe apenas como ponto de passagem." As partículas de intensidade (afetos) vagam sem destino fixo, e as linhas de fuga conectam os pontos mais distantes.',
    params: { organismo:.30, intensidade:.55, hierarquia:.20, rigidez:.20, desorganizacao:.50, crueldade:.40, antiHabito:.60, multiplicidade:.50, linhasDeFuga:.70, territorializacao:.10, reterritorializacao:.10, hubs:.15, esquecimento:.40, ruido:.45, densidade:.50 },
    overlays: ['cso','afetos','rizoma','flights'] },

  { id: 'linhas-de-fuga', name: 'Linhas de Fuga', icon: '⇱',
    description: 'Escape puro. Conexões improváveis dominam.',
    plateauRef: 'Platô 9 · 1933: Micropolítica e segmentaridade',
    theory: 'As linhas de fuga são o terceiro tipo de linha em "Micropolítica": nem molares (segmentos rígidos) nem moleculares (fissuras), são linhas de ruptura absoluta. Conexões improváveis entre pontos distantes que abrem o espaço para o novo. "Uma linha de fuga já é algo complexo, e os perigos que comporta são múltiplos." O escape criativo que desorganiza todos os estratos — mas que também pode se destruir, virar linha de abolição. Observe a proliferação de linhas tracejadas roxas no espaço.',
    params: { organismo:.25, intensidade:.60, hierarquia:.15, rigidez:.15, desorganizacao:.60, crueldade:.35, antiHabito:.65, multiplicidade:.55, linhasDeFuga:.90, territorializacao:.08, reterritorializacao:.05, hubs:.15, esquecimento:.35, ruido:.40, densidade:.55 },
    overlays: ['flights','rizoma','heatConsistency','afetos'] },

  { id: 'devir-animal', name: 'Devir-Animal', icon: '◎',
    description: 'Transformação molecular. Fronteiras de tipo se dissolvem.',
    plateauRef: 'Platô 10 · 1730: Devir-intenso, devir-animal, devir-imperceptível...',
    theory: '"Devir-intenso, devir-animal" descreve como as fronteiras entre espécies, entre tipos, se dissolvem em processos moleculares. Não é imitação nem semelhança: é entrar na zona de indiscernibilidade onde as identidades fixas se transformam. "Devir é, a partir das formas que se tem, do sujeito que se é, extrair partículas entre as quais se instauram relações de velocidade e lentidão mais próximas daquilo em que se está devindo." As partículas de hue variado mostram essa dissolução de fronteiras de tipo.',
    params: { organismo:.30, intensidade:.65, hierarquia:.20, rigidez:.15, desorganizacao:.55, crueldade:.30, antiHabito:.55, multiplicidade:.45, linhasDeFuga:.55, territorializacao:.20, reterritorializacao:.10, hubs:.20, esquecimento:.25, ruido:.40, densidade:.60 },
    overlays: ['cso','afetos','heatConsistency'] },

  { id: 'devir-imperceptivel', name: 'Devir-Imperceptível', icon: '◌',
    description: 'Dissolução gradual. Partículas perdem identidade.',
    plateauRef: 'Platô 10 · 1730: Devir-intenso, devir-animal, devir-imperceptível...',
    theory: 'O devir-imperceptível é o limite de todos os devires: dissolver-se no mundo, tornar-se partícula entre partículas, perder a identidade sem perder a singularidade. "Fazer como todo mundo" — mas de forma que esse "todo mundo" já não signifique nada de molar. "Reduzir-se a uma ou várias linhas abstratas que vão se continuar e se conjugar com outras, para produzir imediatamente, diretamente, um mundo." Observe a baixa densidade, o esquecimento alto — o sistema se dissolve mantendo apenas vestígios de consistência.',
    params: { organismo:.15, intensidade:.45, hierarquia:.10, rigidez:.10, desorganizacao:.70, crueldade:.30, antiHabito:.70, multiplicidade:.30, linhasDeFuga:.50, territorializacao:.10, reterritorializacao:.05, hubs:.10, esquecimento:.50, ruido:.35, densidade:.40 },
    overlays: ['cso','afetos','heatConsistency'] },

  // ── 16-20: CsO (Corpo sem Órgãos) ────────────────────────────────────────
  { id: 'cso-pulsante', name: 'CsO Pulsante', icon: '◉',
    description: 'Intensidades dominam. Pulso vital sem hierarquia.',
    plateauRef: 'Platô 6 · 28 de novembro de 1947: Como criar para si um Corpo sem Órgãos',
    theory: 'O CsO não é o corpo destruído, mas o corpo liberado da organização. Em "28 de novembro de 1947", é descrito como superfície de intensidades puras: sem órgãos que distribuam funções, restam apenas pulsações, fluxos, afetos que percorrem uma superfície sem estratificação. "O CsO é o que resta quando tudo foi retirado. E o que se retira é justamente o fantasma, o conjunto de significâncias e subjetivações." As zonas pulsantes mostram regiões de intensidade que modulam os afetos sem organizá-los.',
    params: { organismo:.10, intensidade:.90, hierarquia:.10, rigidez:.10, desorganizacao:.80, crueldade:.30, antiHabito:.75, multiplicidade:.40, linhasDeFuga:.50, territorializacao:.10, reterritorializacao:.08, hubs:.10, esquecimento:.30, ruido:.45, densidade:.70 },
    overlays: ['cso','afetos','heatConsistency'] },

  { id: 'cso-profundo', name: 'CsO Profundo', icon: '◯',
    description: 'Plano de consistência pleno. Zero especialização.',
    plateauRef: 'Platô 6 · 28 de novembro de 1947: Como criar para si um Corpo sem Órgãos',
    theory: 'O plano de consistência é o CsO levado ao limite: zero especialização, pura imanência. Cada intensidade circula sem obstáculo, sem hierarquia, sem memória. O perigo aqui é o CsO vazio — a catatonia, o corpo esvaziado que nada mais produz. "Tipos ou gêneros de CsO: existem CsO vazios, cancerosos, totalitários, fascistas." Deleuze e Guattari insistem: o CsO é desejo, não destruição. É preciso fazê-lo com prudência. As linhas de fuga e o plano de consistência (azul) coexistem num espaço sem centro.',
    params: { organismo:.05, intensidade:.85, hierarquia:.05, rigidez:.05, desorganizacao:.90, crueldade:.25, antiHabito:.85, multiplicidade:.50, linhasDeFuga:.60, territorializacao:.05, reterritorializacao:.03, hubs:.05, esquecimento:.35, ruido:.50, densidade:.65 },
    overlays: ['cso','afetos','heatConsistency','flights'] },

  { id: 'plano-imanencia', name: 'Plano de Imanência', icon: '∞',
    description: 'Pura imanência. Sem transcendência, puro fluxo.',
    plateauRef: 'Platô 15 · Conclusão: Regras concretas e máquinas abstratas',
    theory: 'Na conclusão de Mil Platôs, o plano de imanência é apresentado como o horizonte de todos os agenciamentos: o campo transcendental sem transcendência, onde tudo coexiste sem hierarquia. "O plano de imanência ou de consistência não é um plano no sentido de um programa, um desígnio, mesmo que virtual. Também não é um plano no sentido de nível ou dimensão. É o plano de proliferação, de povoamento, de contágio." Puro fluxo, sem sujeito, sem objeto — apenas relações de velocidade e lentidão entre partículas.',
    params: { organismo:.05, intensidade:.80, hierarquia:.05, rigidez:.05, desorganizacao:.85, crueldade:.20, antiHabito:.80, multiplicidade:.55, linhasDeFuga:.55, territorializacao:.05, reterritorializacao:.03, hubs:.05, esquecimento:.30, ruido:.55, densidade:.75 },
    overlays: ['cso','afetos','heatConsistency'] },

  { id: 'ovo-intenso', name: 'Ovo Intenso', icon: '◎',
    description: 'O ovo como CsO: superfície pré-organizacional de intensidades.',
    plateauRef: 'Platô 6 · 28 de novembro de 1947: Como criar para si um Corpo sem Órgãos',
    theory: 'O ovo é a metáfora do CsO em estado germinal: superfície pré-organizacional percorrida por intensidades, gradientes, limiares. Antes de haver órgãos, há apenas zonas de intensidade que definem o que o corpo pode. "O ovo intenso é definido por eixos e vetores, gradientes e limiares, tendências dinâmicas com mutação de energia." O ovo intenso é potência pura — observe como a alta densidade de afetos preenche o espaço de forma homogênea, sem hierarquia, como uma superfície vibrante.',
    params: { organismo:.08, intensidade:.95, hierarquia:.05, rigidez:.05, desorganizacao:.85, crueldade:.20, antiHabito:.80, multiplicidade:.35, linhasDeFuga:.40, territorializacao:.08, reterritorializacao:.05, hubs:.05, esquecimento:.20, ruido:.40, densidade:.80 },
    overlays: ['cso','afetos','heatConsistency'] },

  { id: 'delirio-controlado', name: 'Delírio Controlado', icon: '✦',
    description: 'Caos produtivo. Rupturas frequentes geram novos padrões.',
    plateauRef: 'Platô 6 · 28 de novembro de 1947: Como criar para si um Corpo sem Órgãos',
    theory: 'Deleuze e Guattari advertem: é preciso prudência ao criar o CsO. Não se desmonta a organização com golpes de martelo. "Lodged on the stratum, an experimentation on a body without organs can be carried out only prudently." O delírio controlado é a desestratificação prudente — rupturas frequentes mas administráveis, caos produtivo que gera novos padrões sem aniquilar. A crueldade está baixa (rupturas fáceis) mas a multiplicidade e as linhas de fuga mantêm o sistema produtivo, não destrutivo.',
    params: { organismo:.15, intensidade:.90, hierarquia:.12, rigidez:.10, desorganizacao:.80, crueldade:.12, antiHabito:.85, multiplicidade:.65, linhasDeFuga:.70, territorializacao:.08, reterritorializacao:.05, hubs:.10, esquecimento:.40, ruido:.55, densidade:.80 },
    overlays: ['cso','afetos','flights','heatConsistency'] },

  // ── 21-25: RIZOMA (formas de grafo) ───────────────────────────────────────
  { id: 'rizoma-nascente', name: 'Rizoma Nascente', icon: '⊛',
    description: 'Primeiras conexões. Multiplicidade baixa, crescimento lento.',
    plateauRef: 'Platô 1 · Introdução: Rizoma',
    theory: 'A introdução de Mil Platôs apresenta o rizoma como modelo anti-hierárquico: sem começo nem fim, sem centro, múltiplas entradas. "O rizoma conecta um ponto qualquer a outro ponto qualquer, e cada um de seus traços não remete necessariamente a traços de mesma natureza." O rizoma nascente são as primeiras conexões — qualquer ponto pode conectar a qualquer outro, mas o crescimento ainda é tímido. Os diamantes verdes marcam as entradas: portais por onde o rizoma pode ser acessado.',
    params: { organismo:.45, intensidade:.35, hierarquia:.35, rigidez:.35, desorganizacao:.25, crueldade:.45, antiHabito:.20, multiplicidade:.20, linhasDeFuga:.15, territorializacao:.40, reterritorializacao:.30, hubs:.25, esquecimento:.10, ruido:.20, densidade:.45 },
    overlays: ['rizoma','connections','afetos'] },

  { id: 'rizoma-proliferante', name: 'Rizoma Proliferante', icon: '⊞',
    description: 'Crescimento explosivo. Novas entradas surgem constantemente.',
    plateauRef: 'Platô 1 · Introdução: Rizoma',
    theory: 'Os seis princípios do rizoma: 1° e 2° — conexão e heterogeneidade: qualquer ponto pode conectar a qualquer outro. 3° — multiplicidade: não há unidade que sirva de pivô, não há sujeito nem objeto. 4° — ruptura assignificante: pode ser cortado e recomeçar. 5° e 6° — cartografia e decalcomania: o rizoma faz mapa, não decalque. Quando a multiplicidade se intensifica, novas entradas surgem constantemente — o sistema cresce por proliferação, não por divisão hierárquica.',
    params: { organismo:.30, intensidade:.50, hierarquia:.20, rigidez:.20, desorganizacao:.50, crueldade:.40, antiHabito:.50, multiplicidade:.85, linhasDeFuga:.40, territorializacao:.25, reterritorializacao:.15, hubs:.30, esquecimento:.15, ruido:.35, densidade:.55 },
    overlays: ['rizoma','cso','afetos'] },

  { id: 'maquina-guerra', name: 'Máquina de Guerra', icon: '⊠',
    description: 'Rizoma como arma. Conexões improváveis destroem hierarquias.',
    plateauRef: 'Platô 12 · 1227: Tratado de nomadologia — A máquina de guerra',
    theory: 'A máquina de guerra é exterior ao Estado: não nasce para fazer guerra, mas para criar espaço liso. "A máquina de guerra é a invenção dos nômades (enquanto se conjuga com a máquina de guerra nômade)." Em "Tratado de nomadologia", o rizoma se torna arma — conexões improváveis que destroem hierarquias, linhas de fuga que dissolvem os aparelhos de captura. A guerra é o resultado quando o Estado se apropria da máquina de guerra, não sua essência. Observe a proliferação de linhas de fuga (roxas) e a ausência de hubs dominantes.',
    params: { organismo:.20, intensidade:.65, hierarquia:.10, rigidez:.10, desorganizacao:.70, crueldade:.25, antiHabito:.70, multiplicidade:.60, linhasDeFuga:.85, territorializacao:.10, reterritorializacao:.05, hubs:.10, esquecimento:.30, ruido:.50, densidade:.60 },
    overlays: ['rizoma','flights','cso','afetos'] },

  { id: 'rizoma-frio', name: 'Rizoma Frio', icon: '◌',
    description: 'Esquecimento ativo. Estruturas se formam e dissolvem.',
    plateauRef: 'Platô 1 · Introdução: Rizoma',
    theory: 'O rizoma não é eterno — um de seus princípios é a ruptura assignificante: pode ser cortado em qualquer ponto e recomeçar segundo outra de suas linhas. "Todo rizoma compreende linhas de segmentaridade segundo as quais ele é estratificado, territorializado, organizado, significado, atribuído, etc.; mas compreende também linhas de desterritorialização pelas quais ele foge sem parar." O rizoma frio é o esquecimento ativo: estruturas se formam e dissolvem, a poda é tão essencial quanto o crescimento.',
    params: { organismo:.40, intensidade:.25, hierarquia:.35, rigidez:.35, desorganizacao:.30, crueldade:.50, antiHabito:.20, multiplicidade:.30, linhasDeFuga:.20, territorializacao:.35, reterritorializacao:.25, hubs:.30, esquecimento:.80, ruido:.20, densidade:.35 },
    overlays: ['rizoma','connections'] },

  { id: 'rede-acentrada', name: 'Rede Acentrada', icon: '⊡',
    description: 'Sem hierarquia, sem hubs. Igualdade radical de conexões.',
    plateauRef: 'Platô 1 · Introdução: Rizoma',
    theory: 'O rizoma como rede acentrada se opõe tanto à árvore (modelo hierárquico) quanto ao fascículo (falso rizoma com centro oculto). "Diferentemente das árvores ou de suas raízes, o rizoma conecta um ponto qualquer com outro ponto qualquer." Sem hubs, sem hierarquia: igualdade radical de conexões, onde nenhum ponto domina os outros. Observe como a Hub Dominance nos diagnósticos fica próxima de zero — é a rede distribuída em sua forma mais pura, sem captura.',
    params: { organismo:.20, intensidade:.45, hierarquia:.10, rigidez:.15, desorganizacao:.55, crueldade:.40, antiHabito:.50, multiplicidade:.50, linhasDeFuga:.45, territorializacao:.20, reterritorializacao:.15, hubs:.02, esquecimento:.25, ruido:.35, densidade:.50 },
    overlays: ['rizoma','cso','afetos'] },

  // ── 26-30: PLATÔS E COMPOSIÇÕES ───────────────────────────────────────────
  { id: 'simbiose-vibrante', name: 'Simbiose Vibrante', icon: '✧',
    description: 'Equilíbrio dinâmico. Todas as camadas coexistem em harmonia.',
    plateauRef: 'Platô 10 · 1730: Devir-intenso, devir-animal, devir-imperceptível...',
    theory: 'A simbiose vibrante é o platô como estado: um equilíbrio dinâmico onde todas as camadas coexistem sem que uma domine. Como Deleuze e Guattari definem: "Um platô não é um ponto culminante; tampouco está no topo ou no fundo de algo. É uma região contínua de intensidades, vibrando sobre si mesma, sem orientação para um ponto culminante ou uma finalidade exterior." Este é o conceito que nomeia o livro inteiro — cada capítulo é um platô, uma região de intensidade autossuficiente. Observe todas as camadas ativas coexistindo.',
    params: { organismo:.45, intensidade:.55, hierarquia:.40, rigidez:.35, desorganizacao:.35, crueldade:.45, antiHabito:.35, multiplicidade:.40, linhasDeFuga:.35, territorializacao:.35, reterritorializacao:.30, hubs:.30, esquecimento:.20, ruido:.30, densidade:.55 },
    overlays: ['cso','afetos','rizoma','heatConsistency'] },

  { id: 'metastase', name: 'Metástase', icon: '◈',
    description: 'Hubs capturam mas linhas de fuga proliferam. Tensão máxima.',
    plateauRef: 'Platô 13 · 7000 a.C.: Aparelho de captura + Platô 12 · Nomadologia',
    theory: 'A metástase é o ponto de tensão máxima entre captura e fuga: os hubs tentam centralizar enquanto linhas de fuga proliferam. É o momento em que o aparelho de captura e a máquina de guerra coexistem em conflito aberto, sem resolução. "O Estado não para de produzir e de reproduzir segmentos ideais, e a máquina de guerra não para de fazer explodir esses segmentos." Não há síntese dialética aqui — apenas coexistência tensa, processos que se parasitam mutuamente.',
    params: { organismo:.50, intensidade:.60, hierarquia:.45, rigidez:.40, desorganizacao:.45, crueldade:.30, antiHabito:.50, multiplicidade:.55, linhasDeFuga:.60, territorializacao:.30, reterritorializacao:.20, hubs:.65, esquecimento:.20, ruido:.40, densidade:.60 },
    overlays: ['rizoma','flights','cso','afetos'] },

  { id: 'reterritorializacao', name: 'Reterritorialização', icon: '▣',
    description: 'Recaptura gradual. Memória reconstrói territórios perdidos.',
    plateauRef: 'Platô 11 · 1837: Acerca do ritornelo',
    theory: '"Do ritornelo" mostra que toda desterritorialização é acompanhada de reterritorialização: não se pode fugir sem recriar algum tipo de território. "A desterritorialização, por sua vez, deve ser pensada como potência perfeitamente positiva, que tem seus graus e seus limiares (epistrato) e que sempre é relativa, tendo um reverso, uma reterritorialização." A memória reconstrói, o hábito se refaz, mas nunca identicamente — repetição com diferença. O campo de território (âmbar) cresce de volta, mas com outra configuração.',
    params: { organismo:.60, intensidade:.35, hierarquia:.55, rigidez:.50, desorganizacao:.15, crueldade:.50, antiHabito:.10, multiplicidade:.20, linhasDeFuga:.10, territorializacao:.70, reterritorializacao:.80, hubs:.45, esquecimento:.08, ruido:.15, densidade:.45 },
    overlays: ['heatTerritory','connections','afetos'] },

  { id: 'agenciamento', name: 'Agenciamento', icon: '⊕',
    description: 'Composição maquínica. Órgãos + intensidades + rizoma coexistem.',
    plateauRef: 'Platô 15 · Conclusão: Regras concretas e máquinas abstratas',
    theory: 'O agenciamento é o conceito central de Mil Platôs: composição de corpos (agenciamento maquínico de corpos) e enunciados (agenciamento coletivo de enunciação). "Um agenciamento comporta dois segmentos: um de conteúdo, o outro de expressão." É a unidade mínima do pensamento deleuziano: nem sujeito nem objeto, mas a composição que os atravessa. Todo agenciamento tem uma ponta territorial (reterritorialização) e uma ponta de fuga (desterritorialização). Observe como todas as camadas coexistem: órgãos, intensidades, rizoma — agenciadas, não fundidas.',
    params: { organismo:.50, intensidade:.50, hierarquia:.45, rigidez:.40, desorganizacao:.40, crueldade:.40, antiHabito:.40, multiplicidade:.45, linhasDeFuga:.40, territorializacao:.40, reterritorializacao:.30, hubs:.35, esquecimento:.20, ruido:.30, densidade:.55 },
    overlays: ['cso','afetos','rizoma','connections'] },

  { id: 'ritornelo', name: 'Ritornelo', icon: '♻',
    description: 'Repetição com diferença. Ciclos de territorialização e fuga.',
    plateauRef: 'Platô 11 · 1837: Acerca do ritornelo',
    theory: '"Do ritornelo" é talvez o platô mais musical: um motivo sonoro que marca território, que organiza o caos em cosmos. Deleuze e Guattari descrevem três momentos: 1) traçar um centro no caos (a criança que cantarola no escuro), 2) organizar um espaço em torno desse centro (o território como ato expressivo), 3) abrir-se ao cosmos (a linha de fuga do território). "O ritornelo é o conteúdo propriamente musical, o bloco de conteúdo próprio da música." O ciclo — territorializar, desterritorializar, reterritorializar — é o ritmo fundamental, repetição que nunca retorna ao mesmo.',
    params: { organismo:.55, intensidade:.50, hierarquia:.45, rigidez:.40, desorganizacao:.35, crueldade:.40, antiHabito:.35, multiplicidade:.35, linhasDeFuga:.45, territorializacao:.55, reterritorializacao:.50, hubs:.35, esquecimento:.25, ruido:.30, densidade:.50 },
    overlays: ['cso','afetos','heatTerritory','flights'] },
];
