// ── Psyche Lab Presets ────────────────────────────────────────────────────────
// Calibration philosophy (rev 3):
// All presets use a "realistic tempo" — danceIntensity 0.04–0.35, damping 2.5–9.
// The goal is contemplative legibility: you should be able to watch a state
// long enough to actually observe it, not just blur past it.
// "Chaotic" presets are still faster relative to "calm" ones, but the whole
// range is shifted down so every state is watchable.
import { PsycheConfig } from './psycheTypes';

export interface PsychePreset {
  id:          string;
  name:        string;
  description: string;
  observe:     string;
  tags:        string[];
  config:      Partial<PsycheConfig>;
  archetypeStrengths?: Partial<Record<string, number>>;
  archetypeActive?:   string[];
  quantaCount?:       number;
  journeyMode?:       boolean;
}

export const PSYCHE_PRESETS: PsychePreset[] = [

  // ── Clássicos Jung (recalibrados) ─────────────────────────────────────────
  {
    id: 'mandala-calm',
    name: 'Mandala Calm',
    description: 'Estado basal — fluxo harmônico, respiração suave, arquétipos em baixa.',
    observe: 'Fluxo circular lento, integração gradual ao centro, vínculos elásticos aparecem e somem com calma.',
    tags: ['equilíbrio', 'meditação', 'base'],
    config: { danceIntensity: 0.11, maxSpeed: 0.10, breathPeriod: 32, selfPull: 0.28, damping: 4.5, linkMaxTtl: 3.5 },
    archetypeStrengths: { SELF: 0.6, WISE_ONE: 0.5 },
    archetypeActive: ['SELF', 'WISE_ONE', 'MOTHER', 'ANIMA'],
    quantaCount: 2000,
  },
  {
    id: 'ego-inflation',
    name: 'Ego Inflation',
    description: 'Hero e Persona dominam. Superego alto. O Self é ignorado.',
    observe: 'Ordem superficial na região Ego/Persona, Sombra acumulando silenciosamente — o retorno é inevitável.',
    tags: ['inflação', 'persona', 'herói', 'tensão'],
    config: { danceIntensity: 0.19, maxSpeed: 0.16, breathPeriod: 14, selfPull: 0.06, damping: 3.0 },
    archetypeStrengths: { HERO: 0.95, PERSONA: 0.90, FATHER: 0.80, SELF: 0.10, SHADOW: 0.30 },
    archetypeActive: ['HERO', 'PERSONA', 'FATHER', 'SELF', 'SHADOW'],
    quantaCount: 2000,
  },
  {
    id: 'return-of-shadow',
    name: 'Return of the Shadow',
    description: 'Repressão ativa: Superego alto, Sombra acumulando.',
    observe: 'Quanta se aglomeram lentamente no quadrante inferior esquerdo (Sombra). Observe o retorno gradual do reprimido.',
    tags: ['repressão', 'sombra', 'retorno', 'complexo'],
    config: { danceIntensity: 0.22, maxSpeed: 0.18, breathPeriod: 12, selfPull: 0.12, damping: 3.5, linkValDiff: 0.20 },
    archetypeStrengths: { SHADOW: 0.95, FATHER: 0.85, DESTROYER: 0.60, SELF: 0.20, HERO: 0.25 },
    archetypeActive: ['SHADOW', 'FATHER', 'DESTROYER', 'SELF', 'HERO', 'PERSONA'],
    quantaCount: 2000,
  },
  {
    id: 'anima-bridge',
    name: 'Anima Bridge',
    description: 'Anima/Animus ativo: portais Self↔Coletivo abertos. Circulação integrada.',
    observe: 'Circulação suave entre Coletivo e Self central. Vínculos elásticos densos e duradouros.',
    tags: ['anima', 'animus', 'ponte', 'circulação'],
    config: { danceIntensity: 0.14, maxSpeed: 0.12, breathPeriod: 22, selfPull: 0.32, damping: 4.5, linkRadius: 0.09, linkProbability: 0.006, linkMaxTtl: 4.0 },
    archetypeStrengths: { ANIMA: 0.95, SELF: 0.80, LOVER: 0.75, CHILD: 0.60, WISE_ONE: 0.65 },
    archetypeActive: ['ANIMA', 'SELF', 'LOVER', 'CHILD', 'WISE_ONE', 'MOTHER'],
    quantaCount: 2000,
  },
  {
    id: 'trickster-breakthrough',
    name: 'Trickster Breakthrough',
    description: 'Trickster + Destroyer em alta. Limiares baixos. Recombinação criativa.',
    observe: 'Padrões se desfazem e recombinamos. Insights visíveis. Novos clusters emergem do aparente caos.',
    tags: ['trickster', 'caos criativo', 'insight', 'ruptura'],
    config: { danceIntensity: 0.32, maxSpeed: 0.26, breathPeriod: 9, selfPull: 0.14, damping: 2.0, linkMaxTtl: 1.2, linkRadius: 0.055 },
    archetypeStrengths: { TRICKSTER: 0.95, DESTROYER: 0.75, CHILD: 0.80, SHADOW: 0.65, ANIMA: 0.60 },
    archetypeActive: ['TRICKSTER', 'DESTROYER', 'CHILD', 'SHADOW', 'ANIMA'],
    quantaCount: 2000,
  },
  {
    id: 'red-book-journey',
    name: 'Red Book Journey',
    description: 'Jornada guiada do Livro Vermelho em 4 atos (~2.5 min).',
    observe: 'Ato I: Descida. Ato II: Encontros. Ato III: Confronto. Ato IV: Integração.',
    tags: ['guiado', 'Jung', 'Livro Vermelho', '4 atos'],
    config: { danceIntensity: 0.17, maxSpeed: 0.13, breathPeriod: 20, selfPull: 0.22, damping: 3.5, linkMaxTtl: 3.0 },
    archetypeStrengths: {},
    archetypeActive: ['SELF','SHADOW','ANIMA','TRICKSTER','HERO','MOTHER','FATHER','WISE_ONE','CHILD','LOVER','DESTROYER','PERSONA'],
    quantaCount: 2000,
    journeyMode: true,
  },

  // ── Alquimia Jungiana (recalibrada) ───────────────────────────────────────
  {
    id: 'nigredo',
    name: 'Nigredo',
    description: 'A fase negra: dissolução, decomposição, putrefação. Tudo precisa morrer para renascer.',
    observe: 'Clusters se desfazem gradualmente, Sombra domina, alta fragmentação. A matéria prima emerge do colapso.',
    tags: ['alquimia', 'nigredo', 'dissolução', 'shadow'],
    config: { danceIntensity: 0.27, maxSpeed: 0.22, breathPeriod: 7, selfPull: 0.08, damping: 2.5, linkMaxTtl: 0.8, linkRadius: 0.05 },
    archetypeStrengths: { SHADOW: 1.0, DESTROYER: 0.90, TRICKSTER: 0.70, SELF: 0.05 },
    archetypeActive: ['SHADOW', 'DESTROYER', 'TRICKSTER'],
    quantaCount: 2000,
  },
  {
    id: 'albedo',
    name: 'Albedo',
    description: 'A fase branca: purificação, clareza lunar, Anima emerge como guia interior.',
    observe: 'Fluxo luminoso e pausado. Quanta se distribuem em padrões simétricos. Vínculos longos e delicados.',
    tags: ['alquimia', 'albedo', 'purificação', 'anima'],
    config: { danceIntensity: 0.09, maxSpeed: 0.07, breathPeriod: 45, selfPull: 0.42, damping: 5.5, linkMaxTtl: 5.5, linkProbability: 0.008 },
    archetypeStrengths: { ANIMA: 0.95, SELF: 0.85, WISE_ONE: 0.80, MOTHER: 0.70 },
    archetypeActive: ['ANIMA', 'SELF', 'WISE_ONE', 'MOTHER', 'CHILD'],
    quantaCount: 2000,
  },
  {
    id: 'rubedo',
    name: 'Rubedo',
    description: 'A fase vermelha: integração final, o Rei e a Rainha se unem. Opus Magnum.',
    observe: 'Todos os arquétipos dançam juntos com calma majestosa. Auto-organização máxima. O SELF brilha no centro.',
    tags: ['alquimia', 'rubedo', 'integração', 'opus'],
    config: { danceIntensity: 0.16, maxSpeed: 0.12, breathPeriod: 26, selfPull: 0.50, damping: 4.5, linkRadius: 0.10, linkProbability: 0.010, linkMaxTtl: 4.5 },
    archetypeStrengths: { SELF: 1.0, ANIMA: 0.80, HERO: 0.75, WISE_ONE: 0.85, LOVER: 0.75 },
    archetypeActive: ['SELF','ANIMA','HERO','WISE_ONE','LOVER','MOTHER','CHILD'],
    quantaCount: 2000,
  },

  // ── Estados Extremos (recalibrados) ───────────────────────────────────────
  {
    id: 'dark-night',
    name: 'Noite Escura da Alma',
    description: 'São João da Cruz: abandono espiritual total. Deus sumiu. O ego se despedaça.',
    observe: 'Alta fragmentação, SELF quase ausente, movimento pesado. Eventualmente — depois de muito tempo — surge uma centelha de ordem.',
    tags: ['mística', 'crise', 'abandono', 'escuridão'],
    config: { danceIntensity: 0.34, maxSpeed: 0.28, breathPeriod: 6, selfPull: 0.04, damping: 2.0, linkMaxTtl: 0.5 },
    archetypeStrengths: { DESTROYER: 0.95, SHADOW: 0.85, CHILD: 0.60, SELF: 0.02 },
    archetypeActive: ['DESTROYER', 'SHADOW', 'CHILD'],
    quantaCount: 2000,
  },
  {
    id: 'oceanic-feeling',
    name: 'Sentimento Oceânico',
    description: 'Freud/Rolland: dissolução dos limites do ego, fusão com o cosmos.',
    observe: 'Fronteiras entre regiões dissolvem muito lentamente. Fluxo oceânico. Auto-organização difusa e abrangente.',
    tags: ['Freud', 'Rolland', 'oceânico', 'mística'],
    config: { danceIntensity: 0.07, maxSpeed: 0.06, breathPeriod: 55, selfPull: 0.18, damping: 5.5, linkRadius: 0.14, linkProbability: 0.012, linkMaxTtl: 7.0 },
    archetypeStrengths: { SELF: 0.50, MOTHER: 0.85, CHILD: 0.80, LOVER: 0.70, WISE_ONE: 0.60 },
    archetypeActive: ['SELF','MOTHER','CHILD','LOVER','WISE_ONE'],
    quantaCount: 2000,
  },
  {
    id: 'ego-dissolution',
    name: 'Ego Dissolution',
    description: 'Dissolução progressiva do ego (ex.: experiência psicodélica profunda).',
    observe: 'O EGO se fragmenta gradualmente. Quanta vagam além das fronteiras regionais. O coletivo expande.',
    tags: ['dissolução', 'psicodélico', 'self', 'limiar'],
    config: { danceIntensity: 0.24, maxSpeed: 0.19, breathPeriod: 13, selfPull: 0.06, damping: 2.5, linkRadius: 0.12, linkMaxTtl: 1.5 },
    archetypeStrengths: { TRICKSTER: 0.80, CHILD: 0.90, ANIMA: 0.70, SHADOW: 0.60, SELF: 0.30 },
    archetypeActive: ['TRICKSTER','CHILD','ANIMA','SHADOW','SELF'],
    quantaCount: 2000,
  },

  // ── Teoria & Trauma (recalibrados) ────────────────────────────────────────
  {
    id: 'narcissus-mirror',
    name: 'Narciso — O Espelho',
    description: 'Ferida narcísica: ego frágil, Persona rígida, Anima projetada no outro.',
    observe: 'Cluster rígido na Persona. Sombra e Anima completamente separadas. Ressonância com EGO.',
    tags: ['narcisismo', 'espelho', 'persona', 'clínica'],
    config: { danceIntensity: 0.15, maxSpeed: 0.11, breathPeriod: 17, selfPull: 0.08, damping: 3.5, linkValDiff: 0.10 },
    archetypeStrengths: { PERSONA: 1.0, HERO: 0.90, SHADOW: 0.05, ANIMA: 0.20, SELF: 0.10 },
    archetypeActive: ['PERSONA', 'HERO', 'FATHER'],
    quantaCount: 2000,
  },
  {
    id: 'trauma-freeze',
    name: 'Trauma — Congelamento',
    description: 'Resposta de congelamento: toda a energia psíquica paralisada.',
    observe: 'Movimento mínimo, alta inibição. Quanta ficam presos em clusters rígidos. O tempo parece parar.',
    tags: ['trauma', 'freeze', 'inibição', 'clínica'],
    config: { danceIntensity: 0.04, maxSpeed: 0.04, breathPeriod: 80, selfPull: 0.35, damping: 7.0, linkMaxTtl: 9.0 },
    archetypeStrengths: { SHADOW: 0.70, FATHER: 0.80, CHILD: 0.90, SELF: 0.30 },
    archetypeActive: ['SHADOW', 'FATHER', 'CHILD'],
    quantaCount: 2000,
  },
  {
    id: 'grief-processing',
    name: 'Elaboração do Luto',
    description: 'As 5 fases de Kübler-Ross como dinâmica de partículas.',
    observe: 'Oscilação lenta entre fases: negação (clusters rígidos), raiva (leve turbulência), aceitação (fluxo suave).',
    tags: ['luto', 'Kübler-Ross', 'elaboração', 'clínica'],
    config: { danceIntensity: 0.19, maxSpeed: 0.15, breathPeriod: 16, selfPull: 0.22, damping: 3.5, linkMaxTtl: 2.5 },
    archetypeStrengths: { CHILD: 0.85, SHADOW: 0.70, MOTHER: 0.75, DESTROYER: 0.65, SELF: 0.40 },
    archetypeActive: ['CHILD','SHADOW','MOTHER','DESTROYER','SELF','LOVER'],
    quantaCount: 2000,
  },

  // ── Estados de Expansão (recalibrados) ────────────────────────────────────
  {
    id: 'collective-dreaming',
    name: 'Sonho Coletivo',
    description: 'Inconsciente coletivo ativo: imagens primordiais emergindo do fundo.',
    observe: 'Padrões mandaliformes espontâneos. Vínculos densos na região Coletivo. Símbolos emergem devagar.',
    tags: ['inconsciente coletivo', 'sonho', 'imago', 'Jung'],
    config: { danceIntensity: 0.12, maxSpeed: 0.09, breathPeriod: 28, selfPull: 0.26, damping: 4.5, linkRadius: 0.10, linkProbability: 0.007 },
    archetypeStrengths: { WISE_ONE: 0.90, MOTHER: 0.85, CHILD: 0.80, TRICKSTER: 0.60, SELF: 0.70 },
    archetypeActive: ['WISE_ONE','MOTHER','CHILD','TRICKSTER','SELF','ANIMA'],
    quantaCount: 2000,
  },
  {
    id: 'kundalini',
    name: 'Kundalini Rising',
    description: 'Energia de base ascende pelo eixo central — da ID ao SUPEREGO.',
    observe: 'Movimento ascendente lento e concentrado no eixo vertical. Pulsações rítmicas profundas.',
    tags: ['kundalini', 'energia', 'eixo', 'vertical'],
    config: { danceIntensity: 0.21, maxSpeed: 0.16, breathPeriod: 10, selfPull: 0.55, damping: 3.5, linkRadius: 0.06 },
    archetypeStrengths: { HERO: 0.85, SELF: 0.90, DESTROYER: 0.60, WISE_ONE: 0.70, MOTHER: 0.65 },
    archetypeActive: ['HERO','SELF','DESTROYER','WISE_ONE','MOTHER'],
    quantaCount: 2000,
  },
  {
    id: 'synchronicity',
    name: 'Sincronicidade',
    description: 'Coincidências significativas: padrões que conectam interno e externo.',
    observe: 'Vínculos se formam entre partículas distantes de forma improvável. Clusters inesperados. Espelhos.',
    tags: ['sincronicidade', 'Jung', 'padrão', 'coincidência'],
    config: { danceIntensity: 0.14, maxSpeed: 0.10, breathPeriod: 20, selfPull: 0.28, damping: 3.5, linkRadius: 0.16, linkProbability: 0.003, linkMaxTtl: 5.5, linkValDiff: 0.60 },
    archetypeStrengths: { TRICKSTER: 0.85, WISE_ONE: 0.80, SELF: 0.75, CHILD: 0.70 },
    archetypeActive: ['TRICKSTER','WISE_ONE','SELF','CHILD','ANIMA'],
    quantaCount: 2000,
  },
  {
    id: 'flow-state',
    name: 'Estado de Fluxo',
    description: 'Csikszentmihalyi: desafio = habilidade. Atenção total, sem esforço.',
    observe: 'Movimento fluido sem turbulência. Alta coerência, baixa fragmentação. O tempo se dilata.',
    tags: ['fluxo', 'Csikszentmihalyi', 'atenção', 'peak'],
    config: { danceIntensity: 0.17, maxSpeed: 0.14, breathPeriod: 24, selfPull: 0.42, damping: 2.5, linkRadius: 0.08, linkMaxTtl: 4.0 },
    archetypeStrengths: { HERO: 0.80, SELF: 0.90, TRICKSTER: 0.50, CHILD: 0.70, WISE_ONE: 0.75 },
    archetypeActive: ['HERO','SELF','TRICKSTER','CHILD','WISE_ONE'],
    quantaCount: 2000,
  },
  {
    id: 'mystical-union',
    name: 'União Mística',
    description: 'Unio Mystica: a separação sujeito-objeto desaparece. Experiência de não-dualidade.',
    observe: 'Todas as regiões convergem lentamente ao SELF. Vínculos máximos. Pulsação profunda e quieta.',
    tags: ['mística', 'não-dualidade', 'unio', 'integração'],
    config: { danceIntensity: 0.08, maxSpeed: 0.06, breathPeriod: 50, selfPull: 0.62, damping: 5.5, linkRadius: 0.12, linkProbability: 0.010, linkMaxTtl: 7.0 },
    archetypeStrengths: { SELF: 1.0, WISE_ONE: 0.90, LOVER: 0.85, MOTHER: 0.80, CHILD: 0.80 },
    archetypeActive: ['SELF','WISE_ONE','LOVER','MOTHER','CHILD','ANIMA'],
    quantaCount: 2000,
  },
  {
    id: 'hero-complete',
    name: 'Jornada do Herói — Retorno',
    description: 'Campbell: o herói completa o ciclo e traz o elixir. Integração e dom ao mundo.',
    observe: 'HERO retorna ao SELF com sabedoria. WISE_ONE aguarda. O CHILD recebe o dom. Harmonia pausada.',
    tags: ['Campbell', 'herói', 'retorno', 'jornada'],
    config: { danceIntensity: 0.13, maxSpeed: 0.10, breathPeriod: 28, selfPull: 0.40, damping: 4.0, linkMaxTtl: 4.5, linkRadius: 0.09 },
    archetypeStrengths: { HERO: 0.85, SELF: 0.90, WISE_ONE: 0.85, CHILD: 0.75, LOVER: 0.70, TRICKSTER: 0.55 },
    archetypeActive: ['HERO','SELF','WISE_ONE','CHILD','LOVER','TRICKSTER','MOTHER'],
    quantaCount: 2000,
  },
  {
    id: 'creative-fire',
    name: 'Fogo Criativo',
    description: 'A musa desceu: energia criativa expansiva, conexões improváveis.',
    observe: 'Movimento vivaz, vínculos efêmeros. Caos com intenção. Insights emergem como flashes breves.',
    tags: ['criatividade', 'musa', 'inspiração', 'fogo'],
    config: { danceIntensity: 0.28, maxSpeed: 0.23, breathPeriod: 9, selfPull: 0.22, damping: 2.0, linkRadius: 0.07, linkMaxTtl: 1.3, linkProbability: 0.009 },
    archetypeStrengths: { TRICKSTER: 0.90, ANIMA: 0.85, CHILD: 0.85, DESTROYER: 0.65, SELF: 0.50 },
    archetypeActive: ['TRICKSTER','ANIMA','CHILD','DESTROYER','SELF','LOVER'],
    quantaCount: 2000,
  },

  // ── Estados Estáveis — frozenFlow = true ─────────────────────────────────
  {
    id: 'mente-calma',
    name: '🌿 Mente Calma',
    description: 'Estado basal de equilíbrio profundo. Campo congelado, atratores estáticos, quanta em órbita suave ao redor do Self.',
    observe: 'Anéis concêntricos ao redor do Self central. Vínculos longos e persistentes. Alta coerência. A mente encontrou seu centro de gravidade.',
    tags: ['estável', 'equilíbrio', 'self', 'meditação', 'atrator'],
    config: {
      danceIntensity: 0.04, flowGain: 0.20, damping: 9.0, maxSpeed: 0.06,
      breathPeriod: 55, selfPull: 0.80, linkRadius: 0.11, linkProbability: 0.013,
      linkMaxTtl: 12.0, linkValDiff: 0.50, spawnRate: 0.4, deathAge: 400,
      springK: 0.40, frozenFlow: true, stateRelaxRate: 0.25, archetypesOn: true,
    },
    archetypeStrengths: { SELF: 1.0, WISE_ONE: 0.85, MOTHER: 0.70, CHILD: 0.50 },
    archetypeActive: ['SELF', 'WISE_ONE', 'MOTHER'],
    quantaCount: 2000,
  },
  {
    id: 'mente-ansiosa',
    name: '⚡ Mente Ansiosa',
    description: 'Ansiedade crônica: oscilação entre Superego (deveria) e Id (quero), sem resolução. Sistema sub-amortecido — nunca assenta.',
    observe: 'Quanta oscilam entre Superego e Id sem jamais assentar. Vínculos se formam e quebram. Alta inibição, baixa coerência. SELF inacessível.',
    tags: ['estável', 'ansiedade', 'oscilação', 'superego', 'id', 'clínica'],
    config: {
      danceIntensity: 0.08, flowGain: 0.30, damping: 0.70, maxSpeed: 0.28,
      breathPeriod: 3.5, selfPull: 0.03, linkRadius: 0.05, linkProbability: 0.005,
      linkMaxTtl: 0.45, linkValDiff: 0.15, spawnRate: 5, deathAge: 28,
      springK: 0.80, frozenFlow: true, stateRelaxRate: 2.0, archetypesOn: true,
    },
    archetypeStrengths: { FATHER: 0.95, SHADOW: 0.75, DESTROYER: 0.55, SELF: 0.05, HERO: 0.30 },
    archetypeActive: ['FATHER', 'SHADOW', 'DESTROYER'],
    quantaCount: 2000,
  },
  {
    id: 'mente-hedonista',
    name: '🌸 Mente Hedonista',
    description: 'Princípio do prazer (Freud): Id domina, Superego silenciado, toda energia flui para Eros.',
    observe: 'Quanta gravitam entre Id e Ego/Coletivo. Alta valência positiva, baixa inibição. LOVER e MOTHER tecem uma teia de prazer.',
    tags: ['estável', 'hedonismo', 'eros', 'prazer', 'id', 'Freud'],
    config: {
      danceIntensity: 0.07, flowGain: 0.25, damping: 4.5, maxSpeed: 0.12,
      breathPeriod: 9, selfPull: 0.06, linkRadius: 0.10, linkProbability: 0.011,
      linkMaxTtl: 4.5, linkValDiff: 0.55, spawnRate: 1.5, deathAge: 150,
      springK: 0.35, frozenFlow: true, stateRelaxRate: 0.50, archetypesOn: true,
    },
    archetypeStrengths: { LOVER: 1.0, CHILD: 0.85, TRICKSTER: 0.60, MOTHER: 0.75, SHADOW: 0.10, FATHER: 0.05 },
    archetypeActive: ['LOVER', 'CHILD', 'TRICKSTER', 'MOTHER'],
    quantaCount: 2000,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // ── 20 Novos Presets ──────────────────────────────────────────────────────
  // ══════════════════════════════════════════════════════════════════════════

  // ── Clínico ───────────────────────────────────────────────────────────────
  {
    id: 'melancolia',
    name: '🌑 Melancolia',
    description: 'A melancolia de Freud: o objeto perdido foi internalizado. O Ego se identifica com o que perdeu e se volta contra si mesmo.',
    observe: 'Quanta pesados gravitam para a Sombra. Velocidade muito baixa. Valência negativa generalizada. O SELF está lá — mas inacessível, encoberto.',
    tags: ['clínica', 'depressão', 'Freud', 'objeto', 'perda'],
    config: { danceIntensity: 0.06, maxSpeed: 0.05, breathPeriod: 45, selfPull: 0.10, damping: 6.5, linkMaxTtl: 1.2, linkRadius: 0.06 },
    archetypeStrengths: { SHADOW: 0.90, DESTROYER: 0.70, CHILD: 0.80, SELF: 0.15, MOTHER: 0.30 },
    archetypeActive: ['SHADOW', 'DESTROYER', 'CHILD'],
    quantaCount: 2000,
  },
  {
    id: 'hipomania',
    name: '⚡ Hipomania',
    description: 'O polo elevado do espectro bipolar: energia alta, julgamento intacto, prazer em tudo, o mundo parece possível.',
    observe: 'Movimento contínuo e vivaz sem colapso. Alta valência, arousal elevado. Muitos vínculos se formando. HERO e LOVER dançam sem parar.',
    tags: ['clínica', 'bipolar', 'energia', 'expansão'],
    config: { danceIntensity: 0.26, maxSpeed: 0.22, breathPeriod: 8, selfPull: 0.18, damping: 2.5, linkRadius: 0.09, linkProbability: 0.010, linkMaxTtl: 2.5 },
    archetypeStrengths: { HERO: 0.90, LOVER: 0.85, TRICKSTER: 0.80, CHILD: 0.75, SELF: 0.50, DESTROYER: 0.30 },
    archetypeActive: ['HERO','LOVER','TRICKSTER','CHILD','SELF'],
    quantaCount: 2000,
  },
  {
    id: 'toc-compulsao',
    name: '🔄 TOC — Compulsão',
    description: 'Transtorno Obsessivo-Compulsivo: loops repetitivos. O FATHER demanda, o HERO obedece, a SHADOW acumula o que foi evitado.',
    observe: 'Clusters circulam em padrões repetitivos estreitos. Vínculos se formam e se desfazem nos mesmos pontos. Observe os loops.',
    tags: ['clínica', 'TOC', 'compulsão', 'loop', 'repetição'],
    config: { danceIntensity: 0.14, maxSpeed: 0.11, breathPeriod: 6, selfPull: 0.05, damping: 3.0, linkRadius: 0.06, linkValDiff: 0.08, linkMaxTtl: 1.8, springK: 0.85 },
    archetypeStrengths: { FATHER: 1.0, PERSONA: 0.90, SHADOW: 0.60, HERO: 0.70, SELF: 0.10 },
    archetypeActive: ['FATHER', 'PERSONA', 'HERO', 'SHADOW'],
    quantaCount: 2000,
  },
  {
    id: 'dissociacao',
    name: '🔀 Dissociação',
    description: 'O eu se fragmenta em partes que não se comunicam. Partes do self seguem trajetórias paralelas sem encontro.',
    observe: 'Dois ou três clusters isolados que quase não trocam quanta. Poucos vínculos entre regiões. Cada cluster tem sua própria "vida".',
    tags: ['clínica', 'dissociação', 'fragmentação', 'trauma'],
    config: { danceIntensity: 0.10, maxSpeed: 0.08, breathPeriod: 30, selfPull: 0.04, damping: 5.0, linkRadius: 0.04, linkProbability: 0.002, linkValDiff: 0.08, linkMaxTtl: 0.8 },
    archetypeStrengths: { SHADOW: 0.80, CHILD: 0.90, PERSONA: 0.75, DESTROYER: 0.50, SELF: 0.10 },
    archetypeActive: ['SHADOW', 'CHILD', 'PERSONA'],
    quantaCount: 2000,
  },
  {
    id: 'apego-ansioso',
    name: '🫀 Apego Ansioso',
    description: 'Teoria do apego (Bowlby): hipervigilância ao abandono. O CHILD orbita o MOTHER em busca de sinal, nunca satisfeito.',
    observe: 'CHILD oscila em torno da MOTHER sem pousar. Alerta constante. Valência instável. Quando a MOTHER some, emerge o pânico da Sombra.',
    tags: ['clínica', 'apego', 'ansiedade', 'Bowlby', 'CHILD'],
    config: { danceIntensity: 0.16, maxSpeed: 0.14, breathPeriod: 5, selfPull: 0.08, damping: 1.8, linkRadius: 0.07, linkMaxTtl: 1.0, linkValDiff: 0.25 },
    archetypeStrengths: { CHILD: 1.0, MOTHER: 0.80, SHADOW: 0.65, DESTROYER: 0.40, FATHER: 0.55 },
    archetypeActive: ['CHILD', 'MOTHER', 'SHADOW', 'FATHER'],
    quantaCount: 2000,
  },

  // ── Jungiana Avançada ────────────────────────────────────────────────────
  {
    id: 'individuacao-final',
    name: '✦ Individuação — Telos',
    description: 'O fim do processo de individuação jungiano: todos os arquétipos integrados, SELF como centro estável da personalidade total.',
    observe: 'Cada arquétipo ocupa seu lugar natural. Quanta fluem sem tensão entre regiões. O SELF pulsa suavemente no centro. Harmonia genuína.',
    tags: ['Jung', 'individuação', 'integração', 'telos', 'SELF'],
    config: {
      danceIntensity: 0.10, maxSpeed: 0.08, breathPeriod: 40, selfPull: 0.60,
      damping: 5.0, linkRadius: 0.10, linkProbability: 0.009, linkMaxTtl: 6.0,
      frozenFlow: true, stateRelaxRate: 0.30,
    },
    archetypeStrengths: { SELF: 1.0, WISE_ONE: 0.80, ANIMA: 0.80, HERO: 0.70, MOTHER: 0.75, SHADOW: 0.65, CHILD: 0.70, LOVER: 0.75, TRICKSTER: 0.60, FATHER: 0.65, DESTROYER: 0.55, PERSONA: 0.60 },
    archetypeActive: ['SELF','WISE_ONE','ANIMA','HERO','MOTHER','SHADOW','CHILD','LOVER','TRICKSTER','FATHER','DESTROYER','PERSONA'],
    quantaCount: 2000,
  },
  {
    id: 'inflacao-self',
    name: '🌞 Inflação do Self',
    description: 'Identificação com o Self (messianismo, grandiosidade): o ego confunde-se com o arquétipo central. O "eu sou especial" como defesa.',
    observe: 'Todos os quanta tentam orbitar o SELF mas sem damping suficiente — sobrepõem-se, colidem, formam super-clusters instáveis.',
    tags: ['Jung', 'inflação', 'SELF', 'grandiosidade', 'messianismo'],
    config: { danceIntensity: 0.20, maxSpeed: 0.18, breathPeriod: 12, selfPull: 0.90, damping: 1.5, linkRadius: 0.05, linkMaxTtl: 0.6 },
    archetypeStrengths: { SELF: 1.0, HERO: 0.90, WISE_ONE: 0.85, FATHER: 0.80, PERSONA: 0.75 },
    archetypeActive: ['SELF','HERO','WISE_ONE','FATHER','PERSONA'],
    quantaCount: 2000,
  },
  {
    id: 'sonho-lucido',
    name: '🌙 Sonho Lúcido',
    description: 'Consciência dentro do sonho: o ego sabe que sonha, pode interagir com imagens oníricas sem ser arrastado.',
    observe: 'ANIMA guia o movimento, TRICKSTER testa as bordas, CHILD explora. HERO observa com consciência. Padrões oníricos estáveis mas vivos.',
    tags: ['sonho', 'lúcido', 'Jung', 'ANIMA', 'onirismo'],
    config: { danceIntensity: 0.15, maxSpeed: 0.12, breathPeriod: 18, selfPull: 0.30, damping: 3.5, linkRadius: 0.09, linkMaxTtl: 3.5, linkProbability: 0.008 },
    archetypeStrengths: { ANIMA: 0.90, TRICKSTER: 0.80, CHILD: 0.85, HERO: 0.70, WISE_ONE: 0.75, SELF: 0.65 },
    archetypeActive: ['ANIMA','TRICKSTER','CHILD','HERO','WISE_ONE'],
    quantaCount: 2000,
  },

  // ── Contemplativo / Neurológico ───────────────────────────────────────────
  {
    id: 'mindfulness',
    name: '🍃 Mindfulness',
    description: 'Atenção plena ao momento presente: observar sem julgar, sem reter nem empurrar.',
    observe: 'Movimento muito lento e uniforme. Todos os arquétipos ativos mas em baixa intensidade. Quanta distribuídos. Sem aglomeração em nenhuma região.',
    tags: ['mindfulness', 'atenção', 'presente', 'meditação', 'equanimidade'],
    config: {
      danceIntensity: 0.06, maxSpeed: 0.05, breathPeriod: 35, selfPull: 0.35,
      damping: 6.5, linkRadius: 0.08, linkProbability: 0.005, linkMaxTtl: 5.0,
      frozenFlow: true, stateRelaxRate: 0.20,
    },
    archetypeStrengths: { SELF: 0.60, WISE_ONE: 0.55, MOTHER: 0.50, HERO: 0.40, SHADOW: 0.40, CHILD: 0.45, ANIMA: 0.50 },
    archetypeActive: ['SELF','WISE_ONE','MOTHER','CHILD'],
    quantaCount: 2000,
  },
  {
    id: 'estado-hipnotico',
    name: '🌀 Estado Hipnótico',
    description: 'Transe hipnótico: atenção estreitada, sugestionabilidade alta, WISE_ONE como voz interna amplificada.',
    observe: 'Quanta convergem para um foco estreito. Movimentos quase que paralelos. Vínculos se formam rapidamente numa direção única.',
    tags: ['hipnose', 'transe', 'foco', 'atenção', 'sugestionabilidade'],
    config: {
      danceIntensity: 0.07, maxSpeed: 0.06, breathPeriod: 20, selfPull: 0.55,
      damping: 5.5, linkRadius: 0.07, linkProbability: 0.012, linkMaxTtl: 8.0, linkValDiff: 0.12,
      frozenFlow: true, stateRelaxRate: 0.35,
    },
    archetypeStrengths: { WISE_ONE: 1.0, SELF: 0.80, ANIMA: 0.70, PERSONA: 0.60, SHADOW: 0.20 },
    archetypeActive: ['WISE_ONE','SELF','ANIMA'],
    quantaCount: 2000,
  },
  {
    id: 'meditacao-theta',
    name: '🌊 Meditação Theta',
    description: 'Ondas theta (4–8 Hz): limiar entre vigília e sono. Visões hipnagógicas. O mais profundo repouso consciente possível.',
    observe: 'Movimento quase imperceptível. Vínculos duradouros e luminosos. Quanta em órbitas quase circulares. O mandala se autocompleta.',
    tags: ['meditação', 'theta', 'repouso', 'visão', 'silêncio'],
    config: {
      danceIntensity: 0.03, maxSpeed: 0.03, breathPeriod: 70, selfPull: 0.85,
      damping: 11.0, linkRadius: 0.12, linkProbability: 0.015, linkMaxTtl: 15.0, spawnRate: 0.2,
      deathAge: 500, frozenFlow: true, stateRelaxRate: 0.15, archetypesOn: true,
    },
    archetypeStrengths: { SELF: 1.0, WISE_ONE: 0.90, MOTHER: 0.80, ANIMA: 0.75 },
    archetypeActive: ['SELF','WISE_ONE','MOTHER'],
    quantaCount: 2000,
  },

  // ── Ciclos de Vida ────────────────────────────────────────────────────────
  {
    id: 'infancia-primordial',
    name: '🌱 Infância',
    description: 'A psique infantil: CHILD domina, sem repressão, sem Persona formada. Cada coisa é descoberta pela primeira vez.',
    observe: 'Quanta exploram todas as regiões sem medo. Alta renovação (vida curta, renascimento rápido). Vínculos simples e efêmeros. Valência positiva dominante.',
    tags: ['ciclo de vida', 'infância', 'CHILD', 'descoberta', 'inocência'],
    config: { danceIntensity: 0.18, maxSpeed: 0.16, breathPeriod: 10, selfPull: 0.12, damping: 2.5, linkRadius: 0.08, linkMaxTtl: 1.5, spawnRate: 8, deathAge: 20 },
    archetypeStrengths: { CHILD: 1.0, MOTHER: 0.85, LOVER: 0.60, TRICKSTER: 0.70, SELF: 0.30 },
    archetypeActive: ['CHILD','MOTHER','TRICKSTER','LOVER'],
    quantaCount: 2000,
  },
  {
    id: 'velhice-integrada',
    name: '🍂 Velhice Integrada',
    description: 'A senectude jungiana: WISE_ONE acumula, CHILD persiste, HERO descansa. A morte como integração, não derrota.',
    observe: 'Movimento muito lento. Quanta com longa vida, profundamente enraizados em suas regiões. Poucos novos quanta. Coerência acumulada visível.',
    tags: ['ciclo de vida', 'velhice', 'WISE_ONE', 'integração', 'sabedoria'],
    config: {
      danceIntensity: 0.05, maxSpeed: 0.04, breathPeriod: 60, selfPull: 0.50,
      damping: 7.5, linkRadius: 0.09, linkProbability: 0.006, linkMaxTtl: 10.0, spawnRate: 0.3,
      deathAge: 450, frozenFlow: true, stateRelaxRate: 0.20,
    },
    archetypeStrengths: { WISE_ONE: 1.0, SELF: 0.85, MOTHER: 0.80, CHILD: 0.65, HERO: 0.50, ANIMA: 0.70 },
    archetypeActive: ['WISE_ONE','SELF','MOTHER','CHILD'],
    quantaCount: 2000,
  },

  // ── Afetivo-Relacional ────────────────────────────────────────────────────
  {
    id: 'amor-eros',
    name: '💗 Amor — Eros',
    description: 'O amor erótico em seu auge: LOVER e ANIMA/ANIMUS em plena circulação. Eros como força de ligação do mundo.',
    observe: 'Quanta circulam entre EGO e Coletivo em correntes suaves. Vínculos densos e luminosos. Valência muito positiva. SELF como fundo de sustentação.',
    tags: ['amor', 'Eros', 'LOVER', 'ANIMA', 'vínculo'],
    config: { danceIntensity: 0.13, maxSpeed: 0.11, breathPeriod: 14, selfPull: 0.28, damping: 4.0, linkRadius: 0.11, linkProbability: 0.012, linkMaxTtl: 5.0 },
    archetypeStrengths: { LOVER: 1.0, ANIMA: 0.90, CHILD: 0.75, MOTHER: 0.80, SELF: 0.65, HERO: 0.60 },
    archetypeActive: ['LOVER','ANIMA','CHILD','MOTHER','SELF'],
    quantaCount: 2000,
  },
  {
    id: 'desamor',
    name: '💔 Desamor',
    description: 'O fim do amor: ANIMA retirada, projeções desfeitas. O vazio entre quem você era e quem ficou.',
    observe: 'LOVER e ANIMA enfraquecem, SHADOW cresce. Quanta que antes circulavam juntos divergem. Vínculos longos se rompem gradualmente.',
    tags: ['desamor', 'perda', 'ANIMA', 'SHADOW', 'separação'],
    config: { danceIntensity: 0.14, maxSpeed: 0.11, breathPeriod: 22, selfPull: 0.14, damping: 3.5, linkRadius: 0.07, linkMaxTtl: 1.8, linkValDiff: 0.30 },
    archetypeStrengths: { SHADOW: 0.85, DESTROYER: 0.70, CHILD: 0.80, ANIMA: 0.30, SELF: 0.35, LOVER: 0.20 },
    archetypeActive: ['SHADOW','DESTROYER','CHILD','ANIMA','SELF'],
    quantaCount: 2000,
  },
  {
    id: 'amor-materno',
    name: '🌺 Amor Materno',
    description: 'MOTHER como arquétipo central: proteção, nutrição, incondicionalidade. O Self nutrindo o mundo.',
    observe: 'Quanta orbitam a MOTHER em espirais protetoras. CHILD permanece próximo. Alta densidade de vínculos na região Coletivo. Calor e sustentação.',
    tags: ['MOTHER', 'amor', 'nutrição', 'proteção', 'arquétipo'],
    config: {
      danceIntensity: 0.09, maxSpeed: 0.07, breathPeriod: 28, selfPull: 0.42,
      damping: 5.0, linkRadius: 0.12, linkProbability: 0.013, linkMaxTtl: 7.0,
      frozenFlow: true, stateRelaxRate: 0.40,
    },
    archetypeStrengths: { MOTHER: 1.0, CHILD: 0.90, SELF: 0.75, LOVER: 0.70, ANIMA: 0.65, WISE_ONE: 0.60 },
    archetypeActive: ['MOTHER','CHILD','SELF','LOVER'],
    quantaCount: 2000,
  },

  // ── Estados Limítrofes / Criativos ────────────────────────────────────────
  {
    id: 'insight-subito',
    name: '💡 Insight Súbito',
    description: 'O momento "Eureka": ordem brota do caos em flash. TRICKSTER encontra WISE_ONE no mesmo instante.',
    observe: 'Quanta em movimento variado se reorganizam subitamente em torno do SELF. Vínculos improváveis se formam. O campo parece respirar fundo.',
    tags: ['insight', 'criatividade', 'eureka', 'TRICKSTER', 'WISE_ONE'],
    config: { danceIntensity: 0.22, maxSpeed: 0.18, breathPeriod: 12, selfPull: 0.35, damping: 2.8, linkRadius: 0.14, linkProbability: 0.008, linkMaxTtl: 3.5, linkValDiff: 0.55 },
    archetypeStrengths: { TRICKSTER: 0.95, WISE_ONE: 0.90, SELF: 0.80, CHILD: 0.75, ANIMA: 0.70 },
    archetypeActive: ['TRICKSTER','WISE_ONE','SELF','CHILD','ANIMA'],
    quantaCount: 2000,
  },
  {
    id: 'incubacao-criativa',
    name: '🥚 Incubação Criativa',
    description: 'A fase silenciosa da criatividade: a ideia ainda não nasceu, mas está se formando no escuro.',
    observe: 'Aparentemente quieto. Quanta se movem muito devagar, tecendo vínculos sub-visíveis. TRICKSTER e ANIMA trabalham em silêncio. Espere.',
    tags: ['criatividade', 'incubação', 'silêncio', 'processo', 'gestation'],
    config: {
      danceIntensity: 0.06, maxSpeed: 0.05, breathPeriod: 42, selfPull: 0.22,
      damping: 6.0, linkRadius: 0.10, linkProbability: 0.006, linkMaxTtl: 6.5,
      frozenFlow: true, stateRelaxRate: 0.30,
    },
    archetypeStrengths: { TRICKSTER: 0.70, ANIMA: 0.80, CHILD: 0.75, WISE_ONE: 0.65, SHADOW: 0.50, SELF: 0.55 },
    archetypeActive: ['TRICKSTER','ANIMA','CHILD','WISE_ONE','SHADOW'],
    quantaCount: 2000,
  },
  {
    id: 'psicose-limiar',
    name: '🌪 Limiar da Psicose',
    description: 'O limite antes do colapso total: o ego ainda existe mas está sendo arrastado. DESTROYER e SHADOW dominam sem oposição.',
    observe: 'Movimento turbulento com ilhas momentâneas de ordem que se desfazem. Quanta cruzam fronteiras regionais aleatoriamente. Tensão extrema.',
    tags: ['clínica', 'psicose', 'limiar', 'DESTROYER', 'colapso'],
    config: { danceIntensity: 0.35, maxSpeed: 0.30, breathPeriod: 4, selfPull: 0.02, damping: 1.5, linkMaxTtl: 0.3, linkRadius: 0.06, spawnRate: 7, deathAge: 15 },
    archetypeStrengths: { DESTROYER: 1.0, SHADOW: 0.90, TRICKSTER: 0.75, CHILD: 0.70, SELF: 0.05, HERO: 0.20 },
    archetypeActive: ['DESTROYER','SHADOW','TRICKSTER','CHILD'],
    quantaCount: 2000,
  },
  {
    id: 'sabedoria-trickster',
    name: '🃏 Sabedoria do Trickster',
    description: 'O Trickster maduro: não mais puro caos, mas o caos que serve à transformação. A sabedoria que só vem pela disrupção.',
    observe: 'Padrões se formam e se desfazem ciclicamente. TRICKSTER e WISE_ONE alternando influência. Caos com ritmo reconhecível.',
    tags: ['Trickster', 'sabedoria', 'transformação', 'ciclo', 'paradoxo'],
    config: { danceIntensity: 0.20, maxSpeed: 0.16, breathPeriod: 11, selfPull: 0.25, damping: 2.5, linkRadius: 0.08, linkMaxTtl: 2.5, linkProbability: 0.007 },
    archetypeStrengths: { TRICKSTER: 0.95, WISE_ONE: 0.85, SHADOW: 0.70, SELF: 0.75, CHILD: 0.65, DESTROYER: 0.55 },
    archetypeActive: ['TRICKSTER','WISE_ONE','SHADOW','SELF','CHILD'],
    quantaCount: 2000,
  },
  {
    id: 'complexo-paterno',
    name: '⚔️ Complexo Paterno',
    description: 'A sombra do FATHER: lei, limite, julgamento. Pode ser libertador ou aprisionante. Hero tenta escapar, Persona obedece.',
    observe: 'FATHER domina o Superego com força. HERO e PERSONA orbitam tensamente. CHILD recuado. SHADOW cresce nos limites.',
    tags: ['complexo', 'FATHER', 'lei', 'autoridade', 'clínica'],
    config: { danceIntensity: 0.17, maxSpeed: 0.14, breathPeriod: 14, selfPull: 0.10, damping: 3.5, linkRadius: 0.07, linkValDiff: 0.18, linkMaxTtl: 2.5 },
    archetypeStrengths: { FATHER: 1.0, PERSONA: 0.85, HERO: 0.75, SHADOW: 0.70, CHILD: 0.40, SELF: 0.25 },
    archetypeActive: ['FATHER','PERSONA','HERO','SHADOW','CHILD'],
    quantaCount: 2000,
  },
];

export function getPreset(id: string): PsychePreset | undefined {
  return PSYCHE_PRESETS.find(p => p.id === id);
}

export function getPresetName(id: string): string {
  return PSYCHE_PRESETS.find(p => p.id === id)?.name ?? id;
}
