// ─────────────────────────────────────────────────────────────────────────────
// Hermetic Journey Presets — Tree of Life Lab (Golden Dawn tradition)
// ─────────────────────────────────────────────────────────────────────────────
import type { JourneyPreset, TreeOfLifeParams } from './types';

export const JOURNEY_PRESETS: JourneyPreset[] = [
  {
    id: 'neophyte',
    name: 'Neophyte Awakening',
    emoji: '🕯',
    description: 'Enter at Malkuth. First steps on the path. Gentle, exploratory.',
    recommendedLens: 'rws',
    drawRate: 3,
    strictness: 0.35,
    veilsEnabled: false,
    pillarsEnabled: true,
    gdGrade: '0°=0□ Neophyte',
    ritualTheme: 'Purification and dedication',
    initialState: {
      malkuth:   { charge: 0.60, coherence: 0.30, tension: 0.10, openness: 0.65, memory: 0.15 },
      yesod:     { charge: 0.25, coherence: 0.15, openness: 0.45 },
      tiphereth: { charge: 0.10, coherence: 0.10, openness: 0.30 },
    },
  },
  {
    id: 'middlepillar',
    name: 'Middle Pillar Ritual',
    emoji: '⚡',
    description: 'Kether to Malkuth along the axis of equilibrium. Classic GD practice.',
    recommendedLens: 'rws',
    drawRate: 3,
    strictness: 0.50,
    veilsEnabled: true,
    pillarsEnabled: true,
    gdGrade: '2°=9□ Theoricus',
    ritualTheme: 'Equilibrium and circulation of light',
    initialState: {
      kether:    { charge: 0.40, coherence: 0.55, tension: 0.05, openness: 0.50, memory: 0.25 },
      tiphereth: { charge: 0.50, coherence: 0.45, tension: 0.15, openness: 0.60 },
      yesod:     { charge: 0.45, coherence: 0.35, tension: 0.15, openness: 0.55 },
      malkuth:   { charge: 0.55, coherence: 0.30, tension: 0.15, openness: 0.65 },
    },
  },
  {
    id: 'lbrp',
    name: 'Lesser Banishing',
    emoji: '✦',
    description: 'Cleanse the astral temple. High structure, Marseille precision.',
    recommendedLens: 'marseille',
    drawRate: 3,
    strictness: 0.70,
    veilsEnabled: false,
    pillarsEnabled: true,
    gdGrade: '1°=10□ Zelator',
    ritualTheme: 'Banishing and protection',
    initialState: {
      geburah:   { charge: 0.50, coherence: 0.40, tension: 0.30, openness: 0.40 },
      binah:     { charge: 0.35, coherence: 0.35, tension: 0.20 },
      malkuth:   { charge: 0.55, coherence: 0.40, tension: 0.20 },
    },
  },
  {
    id: 'alchemical',
    name: 'Alchemical Great Work',
    emoji: '🜁',
    description: 'Solve et Coagula. Thoth lens. High energy transformative flux.',
    recommendedLens: 'thoth',
    drawRate: 5,
    strictness: 0.35,
    veilsEnabled: false,
    pillarsEnabled: false,
    gdGrade: '5°=6□ Adeptus Minor',
    ritualTheme: 'Nigredo, Albedo, Rubedo — the alchemical stages',
    initialState: {
      netzach:   { charge: 0.70, coherence: 0.20, tension: 0.40, openness: 0.80 },
      chesed:    { charge: 0.60, coherence: 0.25, tension: 0.30 },
      tiphereth: { charge: 0.55, coherence: 0.30, tension: 0.25 },
    },
  },
  {
    id: 'astralvision',
    name: 'Astral Scrying',
    emoji: '🔮',
    description: 'Yesod-centred dreamwork. Moon cycles, memory loops, subtle visions.',
    recommendedLens: 'rws',
    drawRate: 4,
    strictness: 0.30,
    veilsEnabled: false,
    pillarsEnabled: true,
    gdGrade: '2°=9□ Theoricus',
    ritualTheme: 'Lunar scrying and astral travel',
    initialState: {
      yesod:   { charge: 0.65, coherence: 0.15, tension: 0.20, memory: 0.55, openness: 0.60 },
      hod:     { charge: 0.40, coherence: 0.20, tension: 0.25, memory: 0.35 },
      netzach: { charge: 0.45, coherence: 0.15, tension: 0.30, memory: 0.30 },
    },
  },
  {
    id: 'abysscrossing',
    name: 'Crossing the Abyss',
    emoji: '🌑',
    description: 'Maximum challenge. Veils on, high tension. Dare the Dweller on the Threshold.',
    recommendedLens: 'thoth',
    drawRate: 5,
    strictness: 0.90,
    veilsEnabled: true,
    pillarsEnabled: true,
    gdGrade: '8°=3□ Magister Templi',
    ritualTheme: 'Dissolution of ego at the Abyss',
    initialState: {
      geburah:   { charge: 0.80, tension: 0.60, coherence: 0.10, openness: 0.25 },
      binah:     { charge: 0.70, tension: 0.50, coherence: 0.15, openness: 0.30 },
      malkuth:   { charge: 0.65, tension: 0.45, coherence: 0.20, openness: 0.35 },
    },
  },
  {
    id: 'rosecross',
    name: 'Rose Cross Meditation',
    emoji: '🌹',
    description: 'Tiphareth-centred heart ritual. Balance, beauty, and the inner sun.',
    recommendedLens: 'rws',
    drawRate: 4,
    strictness: 0.45,
    veilsEnabled: false,
    pillarsEnabled: true,
    gdGrade: '5°=6□ Adeptus Minor',
    ritualTheme: 'The Rosy Cross — union of opposites at the heart',
    initialState: {
      tiphereth: { charge: 0.65, coherence: 0.50, tension: 0.10, openness: 0.70, memory: 0.30 },
      chesed:    { charge: 0.40, coherence: 0.35, tension: 0.15 },
      geburah:   { charge: 0.40, coherence: 0.35, tension: 0.15 },
      netzach:   { charge: 0.35, coherence: 0.25, openness: 0.55 },
      hod:       { charge: 0.35, coherence: 0.25, openness: 0.55 },
    },
  },
  {
    id: 'elemental',
    name: 'Elemental Initiation',
    emoji: '🜂',
    description: 'Journey through Earth, Water, Air, Fire. Four lower grades in sequence.',
    recommendedLens: 'marseille',
    drawRate: 4,
    strictness: 0.55,
    veilsEnabled: false,
    pillarsEnabled: true,
    gdGrade: '1°=10□ to 4°=7□',
    ritualTheme: 'Elemental grades and purification',
    initialState: {
      malkuth: { charge: 0.55, coherence: 0.35, tension: 0.15, openness: 0.50 },
      yesod:   { charge: 0.40, coherence: 0.25, tension: 0.20, openness: 0.50 },
      hod:     { charge: 0.35, coherence: 0.20, tension: 0.25, openness: 0.45 },
      netzach: { charge: 0.35, coherence: 0.20, tension: 0.25, openness: 0.45 },
    },
  },
];

export const DEFAULT_PARAMS: TreeOfLifeParams = {
  deckLens:        'rws',
  preset:          'neophyte',
  veilsEnabled:    false,
  pillarsEnabled:  true,
  drawRate:        3,
  strictness:      0.40,
  ritualIntensity: 0.50,
  astralClarity:   0.50,
  speed:           1.0,
};
